CREATE DATABASE /*!32312 IF NOT EXISTS*/`ssr` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `ssr`;

DROP TABLE IF EXISTS `ssr_dynamic_sql`;

CREATE TABLE `ssr_dynamic_sql` (
   `ID` varchar(32) NOT NULL COMMENT '主键',
   `QUERY_CODE` varchar(100) NOT NULL COMMENT '查询的code',
   `QUERY_NAME` varchar(100) DEFAULT NULL COMMENT '查询的名称',
   `QUERY_TYPE` varchar(50) DEFAULT NULL COMMENT '查询的类型',
   `SQL_TEMPLATE` text NOT NULL COMMENT 'sql模板',
   `PRE_SCRIPT` text COMMENT '预处理脚本',
   `BEFORE_SCRIPT` text COMMENT '查询之前脚本',
   `AFTER_SCRIPT` text COMMENT '查询之后脚本',
   `VERSION` varchar(20) DEFAULT NULL COMMENT '版本号',
   `DEL_FLAG` bit(1) DEFAULT NULL COMMENT '是否删除。1：是，0：否。',
   `ORDER_NUM` int(11) DEFAULT NULL COMMENT '排序编号。正序。',
   `CREATE_NAME` varchar(60) DEFAULT NULL COMMENT '创建人名称',
   `CREATE_Id` varchar(64) DEFAULT NULL COMMENT '创建人id',
   `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
   `UPDATE_NAME` varchar(60) DEFAULT NULL COMMENT '修改人名称',
   `UPDATE_Id` varchar(64) DEFAULT NULL COMMENT '修改人id',
   `UPDATE_TIME` datetime DEFAULT NULL COMMENT '修改时间',
   `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
   PRIMARY KEY (`ID`),
   UNIQUE KEY `UNIQUE` (`QUERY_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- test
DROP TABLE IF EXISTS `ssr_user`;

CREATE TABLE `ssr_user` (
    `ID` int(32) NOT NULL AUTO_INCREMENT,
    `NAME` varchar(32) DEFAULT NULL,
    `USER_NAME` varchar(32) DEFAULT NULL,
    `CODE` varchar(32) DEFAULT NULL,
    `PASSWORD` varchar(32) DEFAULT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;